PROG = 7zz

CONSOLE_VARIANT_FLAGS=-DZ7_PROG_VARIANT_Z

# IS_X64 = 1
# USE_ASM = 1
# ST_MODE = 1

include ../Format7zF/Arc_gcc.mak

ifdef SystemDrive
IS_MINGW = 1
else
ifdef SYSTEMDRIVE
# ifdef OS
IS_MINGW = 1
endif
endif

LOCAL_FLAGS_SYS =

ifdef IS_MINGW

LOCAL_FLAGS_SYS = \
  -DZ7_DEVICE_FILE \

#  -DZ7_LONG_PATH \
#  -DZ7_DEVICE_FILE \

SYS_OBJS = \
  $O/FileSystem.o \
  $O/Registry.o \
  $O/MemoryLock.o \
  $O/DLL.o \
  $O/DllSecur.o \
  $O/resource.o \

else

SYS_OBJS = \
  $O/MyWindows.o \

endif


LOCAL_FLAGS = \
  $(LOCAL_FLAGS_SYS) \
  $(LOCAL_FLAGS_ST) \


UI_COMMON_OBJS = \
  $O/ArchiveCommandLine.o \
  $O/ArchiveExtractCallback.o \
  $O/ArchiveOpenCallback.o \
  $O/Bench.o \
  $O/DefaultName.o \
  $O/EnumDirItems.o \
  $O/Extract.o \
  $O/ExtractingFilePath.o \
  $O/HashCalc.o \
  $O/LoadCodecs.o \
  $O/OpenArchive.o \
  $O/PropIDUtils.o \
  $O/SetProperties.o \
  $O/SortUtils.o \
  $O/TempFiles.o \
  $O/Update.o \
  $O/UpdateAction.o \
  $O/UpdateCallback.o \
  $O/UpdatePair.o \
  $O/UpdateProduce.o \

CONSOLE_OBJS = \
  $O/BenchCon.o \
  $O/ConsoleClose.o \
  $O/ExtractCallbackConsole.o \
  $O/HashCon.o \
  $O/List.o \
  $O/Main.o \
  $O/MainAr.o \
  $O/OpenCallbackConsole.o \
  $O/PercentPrinter.o \
  $O/UpdateCallbackConsole.o \
  $O/UserInputUtils.o \

COMMON_OBJS_2 = \
  $O/CommandLineParser.o \
  $O/ListFileUtils.o \
  $O/StdInStream.o \
  $O/StdOutStream.o \

WIN_OBJS_2 = \
  $O/ErrorMsg.o \
  $O/FileLink.o \
  $O/SystemInfo.o \

7ZIP_COMMON_OBJS_2 = \
  $O/FilePathAutoRename.o \
  $O/FileStreams.o \
  $O/MultiOutStream.o \

OBJS = \
  $(ARC_OBJS) \
  $(SYS_OBJS) \
  $(COMMON_OBJS_2) \
  $(WIN_OBJS_2) \
  $(7ZIP_COMMON_OBJS_2) \
  $(UI_COMMON_OBJS) \
  $(CONSOLE_OBJS) \

_COMPRESS_OBJS = \
  $O/Bcj2Coder.o \
  $O/Bcj2Register.o \
  $O/BcjCoder.o \
  $O/BcjRegister.o \
  $O/BitlDecoder.o \
  $O/BranchMisc.o \
  $O/BranchRegister.o \
  $O/ByteSwap.o \
  $O/BZip2Crc.o \
  $O/BZip2Decoder.o \
  $O/BZip2Encoder.o \
  $O/BZip2Register.o \
  $O/CopyCoder.o \
  $O/CopyRegister.o \
  $O/Deflate64Register.o \
  $O/DeflateDecoder.o \
  $O/DeflateEncoder.o \
  $O/DeflateRegister.o \
  $O/DeltaFilter.o \
  $O/ImplodeDecoder.o \
  $O/Lzma2Decoder.o \
  $O/Lzma2Encoder.o \
  $O/Lzma2Register.o \
  $O/LzmaDecoder.o \
  $O/LzmaEncoder.o \
  $O/LzmaRegister.o \
  $O/LzOutWindow.o \
  $O/LzxDecoder.o \
  $O/PpmdDecoder.o \
  $O/PpmdEncoder.o \
  $O/PpmdRegister.o \
  $O/PpmdZip.o \
  $O/QuantumDecoder.o \
  $O/ShrinkDecoder.o \
  $O/XzDecoder.o \
  $O/XzEncoder.o \
  $O/ZstdDecoder.o \

include ../../7zip_gcc.mak
