on:
  workflow_dispatch:
  push:
    branches:
      - Dark7zip-zstd-7zz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile/Build project (Example)
        run: git clone https://github.com/Lichtenshtein/Dark7zip-zstd-7zz && cd Dark7zip-zstd-7zz/CPP/7zip/Bundles/Alone2 && nmake PLATFORM=x64
        
      - name: Prepare artifact
        shell: pwsh
        run: |
          mkdir asset
          cp Dark7zip-zstd-7zz/CPP/7zip/Bundles/Alone2/x64/7zz.exe asset/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-output
          path: asset/
