name: Build Windows binaries
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x64, x64_x86, x64_arm64 ]
        include:
          - arch: x64
            platform: x64
          - arch: x64_x86
            platform: x86
          - arch: x64_arm64
            platform: arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ${{ matrix.arch }}
        shell: cmd
        run: |
          build.cmd ${{ matrix.platform }}

      - name: Archive artifact ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: 7z-dark-${{ matrix.platform }}
          path: ${{ matrix.platform }}-bin

      - name: Archive artifact ${{ matrix.platform }} with fluent icons
        if: ${{ matrix.platform == 'x64' || matrix.platform == 'arm64' }}
        uses: actions/upload-artifact@v4
        with:
          name: 7z-dark-${{ matrix.platform }}-fluent-toolbar-icons
          path: ${{ matrix.platform }}-fluent-bin
